READ_LINES = 240
REPOSITORY_EXPANSION_CALL_LIMIT = 16
REPOSITORY_REFUTATION_CALL_RESERVE = 4
MANDATORY_REPOSITORY_READ_LIMIT = (
    REPOSITORY_EXPANSION_CALL_LIMIT - REPOSITORY_REFUTATION_CALL_RESERVE
)
CLAUDE_MAX_TURNS = 160
PROVIDER_TURN_RESERVE = 2
